### ISSUE TITLE
backup_label : return immediately CRITICAL on secondary, or when pg_is_in_backup() = false

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/check_pgactivity#322]
- A backup_label on a secondary server is not normal and dangerous.
The service should return CRITICAL immediately.

- If pg_is_backup () is false, it should return CRITICAL too
(that would cover the previous case).

**Comment by frost242** [comment]
Hello,
One problem I see with this change is that this checks will not be possible on PG >= 9.3 AND < 10 without being superuser (use of pg_ls_dir.
Fortunately, pg_ls_waldir() saves it with PG10.

If it's OK to support this behavior from PG10+, I'll provide a patch quickly.

**Comment by frost242** [comment]
Hello,
I've just pushed some changes regarding backup_label_age, but this does not address this issue. Are you willing to push a PR to fix this in the near future ?

**Comment by gleu** [comment]
I guess you meant pg_is_in_backup(). This function doesn't exist anymore since the v15 release. I guess this point is moot then?

The issue on backup_label on a secondary seems something to take care though.

**Comment by gleu** [comment]
This file doesn't exist anymore since the v15 release. Might be useful on prior releases, but I fail to see how usefull that would be.

**Comment by Krysztophe** [comment]
`backup_label` still exists on PG19 (pg_basebackup creates one, for example)
It is renamed as backup_label.old after use, so it should never be there (v15+),
whatever its age.
But it should appear only in the backup and should have disappeared after the restore.

On v14 and previous, `backup_label` should not exist on a secondary ( ` pg_start_backup ('nom',true,true);` fails.)

So this issue should be renamed:
> backup_label_age: fails immediately if `backup_label` present on a secondary or PG15+

With PG14 out of support, it's less useful, so no real need to rename.
I cannot think of a case where a `backup_label` appeared erroneously in the PGDATA of a running instance.

If you agree, I can do the patch.

**Comment by gleu** [comment]
Go ahead, work on the patch. Thank you.

**Comment by Krysztophe** [comment]
PR #441 done (without tests yet) for raising an alert on PG15+

It does not include the check on the secondary server. 
Is it worth it, with PG14 soon out of support?

**Comment by gleu** [comment]
I guess you could avoid it for now. If someone asks for it, it will be time to add it.
